server.port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false			# 设为false，关闭自我保护
    server.eviction-interval-timer-in-ms: 5000     # 清理间隔（单位毫秒，默认是60*1000）