server.port: 9090
eureka.instance.appname: service.provider
eureka.client.serviceUrl.defaultZone: http://10.195.225.39:8762/eureka/,http://10.195.225.39:8761/eureka/

eureka.instance.leaseRenewalIntervalInSeconds: 10
eureka.client.registryFetchIntervalSeconds: 5