server.port: 8888
spring.application.name: configserver
spring.cloud.config.uri: http://localhost:8888


spring.cloud.config.server.svn.uri: http://10.195.7.112/AMEKMS/
spring.cloud.config.server.svn.basedir: D:\web\temps
spring.cloud.config.server.svn.password: hztpm.60
spring.cloud.config.server.svn.username: F3219057
spring.cloud.config.enabled: true 
#spring.cloud.config.server.default-label: Trunk
spring.profiles.active: subversion
spring.main.show-banner: false

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG
